---
title: "Mapping-Rmd"
author: "Bouzaher, Julia"
date: "September 22, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's test the shapefile.


```{r}
library(rgeos)
library(sp)
library(sf)
library(rgeos)
library(magrittr)
library(dplyr)
library(readr)
library(gridExtra)
library(ggplot2)
library(data.table)
library(rgdal)
library(lubridate)
library(spatstat)
library(stringr)
library(rgdal)
library(sf) 
library(sp)
library(rgeos)
library(leaflet)
library(raster)
library(dplyr)
library(maptools)
library(tidyverse)
library(lwgeom)
library(spatialEco)
library(stats)

```

```{r}
shape <- read_sf("data/source/external/tract shapefiles [tract]/tl_2019_39_tract.shp") %>%
  filter(COUNTYFP =="043")

factpal <- colorFactor(palette = magma(19), domain = shape$TRACTCE)
 
# leaflet(shape) %>%
#   addProviderTiles(providers$OpenStreetMap) %>%
#   addPolygons(weight=1.4, fillColor = ~factpal(shape$TRACTCE), fillOpacity = 1

final <- full_join(final,shape, by="NAMELSAD") %>%
  mutate(tract = NAMELSAD) %>%
  dplyr::select(-(c(STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,INTPTLON,INTPTLAT))) %>%
  mutate(medianincome = as.numeric(final$`Median household income`))


final <- st_sf(final)
final <- st_transform(final, 4326)
```

Map 1: Distribution of Black/African American Population

```{r}

factpal <- viridis(length(final$Black))
factpal <- colorNumeric(palette = viridis(997), c(0,997))

#final <- final %>% filter(year == "2016")

leaflet(final) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(weight=1.4, fillColor = ~factpal(as.numeric(final$Black)), fillOpacity=1) %>%
  addLegend(position ="bottomleft", pal = factpal, values = as.numeric(final$Black), title = "Number of Black Individuals",labFormat = labelFormat(suffix = " individuals"), opacity=1)


```

Map 2: Distribution of Median Rents

```{r}

range(final$MedianRent)
factpal <- colorNumeric(palette = viridis(500), c(500,1000))

map <- leaflet(final %>% filter(year == "2018")) %>%
  addTiles() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(label = ~paste ("Tract:",tract, "\nMedian Rent:",MedianRent),
              fillColor = ~factpal(as.numeric(MedianRent)),
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1.0,
              fillOpacity = .88,
              highlightOptions = highlightOptions(color = "white",
                                                  weight = 2,
                                                  bringToFront = TRUE)) %>%
  addLegend(position ="bottomleft", pal = factpal, values = as.numeric(final$MedianRent), title = "Median Rents 2018",labFormat = labelFormat(prefix = "$"), opacity=1)

```

Let's take a look at our other files.

```{r}
real_estate_db <- read_csv("data/source/external/mortgage [county]/real_estate_db.csv") %>%
  filter(state=="Ohio") %>%
  filter(city=="Sandusky")
```

```{r}
voting <- read_sf("data/source/city/Erie County Voting Precincts/Erie_County_Voting_Precincts.shp")
```

```{r}
GLRI <- read_sf("data/source/city/GLRI Pathway/Polygon_layer.shp")
GLRI <- st_transform(GLRI, 4326)

leaflet(GLRI) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons()

```

```{r}
Landmarks <- read_sf("data/source/city/Landmarks/Landmarks_ft.shp")
Landmarks <- st_transform(Landmarks, 4326)

leaflet(Landmarks) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addCircleMarkers(radius=.2)

```


```{r}
# Model_Blocks <- read_sf("data/source/city/Model_Blocks/Model_Blocks.shp")
# Model_Blocks <- st_transform(Model_Blocks, 4326)
# 
# leaflet(Model_Blocks) %>%
#   addProviderTiles(providers$OpenStreetMap) %>%
#   addPolygons()

```

```{r}
Neighborhoods <- read_sf("data/source/city/Neighborhoods/City_of_Sandusky_Neighborhoods.shp")
Neighborhoods <- st_transform(Neighborhoods, 4326)

leaflet(Neighborhoods) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons()

```

```{r}
Erie_County_Plan <- read_sf("data/source/city/Sandusky Bay Pathway/2014_Erie_County_Plan.shp")
Erie_County_Plan <- st_transform(Erie_County_Plan, 4326)

leaflet(Erie_County_Plan) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons()

```





```{r}

#wetlands data

library(raster)
Wetlands <- read_sf("data/source/external/wetlands data/HU8_04100011_Watershed/HU8_04100011_Wetlands.shp")
Wetlands2 <- read_sf("data/source/external/wetlands data/HU8_04100012_Watershed/HU8_04100012_Wetlands.shp")

Wetlands <- st_transform(Wetlands, CRS("+init=epsg:4326"))
Wetlands2 <- st_transform(Wetlands2, CRS("+init=epsg:4326"))

Wetlands3 <- rbind(Wetlands, Wetlands2)

Wetlands3 <- st_crop(Wetlands3, xmin = -82.918968, xmax = -82.314877,  ymin = 41.277963, ymax = 41.483993)


#parks names data
parks <- fread("data/source/external/Parks/OH_Features_20200901.txt") %>%
  filter(COUNTY_NAME == "Erie") %>%
  filter(FEATURE_CLASS == "Park") %>%
  rename(lat = PRIM_LAT_DEC, long = PRIM_LONG_DEC)

#land cover data



leafIcons <- icons(
  iconUrl = 
    "http://leafletjs.com/examples/custom-icons/leaf-green.png",
  iconWidth = 15, iconHeight = 40,
  iconAnchorX = 14, iconAnchorY = 40
)


```

```{r}
bps2016 <- raster::raster("data/source/external/landcover data/US_200BPS/us_200bps/w001001.adf")
#pure land cover

landcover2016 <- raster::raster("data/source/external/landcover data/US_200EVC/us_200evc/w001001.adf")

landcover2014 <- raster::raster("data/source/external/landcover data/US_140EVC/us_140evc/w001001.adf")

landcover2012 <- raster::raster("data/source/external/landcover data/US_130EVC/us_130evc/w001001.adf")

landcover2010 <- raster::raster("data/source/external/landcover data/US_120EVC/us_120evc/w001001.adf")

landcover2008<- raster::raster("data/source/external/landcover data/US_110EVC/us_110evc/w001001.adf")

landcover2001 <- raster::raster("data/source/external/landcover data/US_105EVC/us_105evc/w001001.adf") 

landcoverchange10 <- raster::raster("data/source/external/landcover data/US_VTM2010/us_vtm2010/w001001.adf")

landcoverchange14 <- raster::raster("data/source/external/landcover data/US_VTM2014/us_vtm2014/w001001.adf")

 
```


Setting Up
```{r}
# labels22001<- c("Developed - Forested", "Developed - herbaceous or shrubland", "Developed - Low Intensity", "Developed - Medium Intensity", "Developed - High Intensity", "Herbaceous Wetlands", "Tree Cover 0-50%", "Tree Cover 50-100%", "Herb Cover 0-50%", "Herb Cover 50-100%", "Shrub Cover", "Cropland", "Barren or Quarry Land")



#landcover 2001

landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] <- 500 
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")] <- 501
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] <- 502 
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")] <- 503
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")] <- 504   
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")] <- 505
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")] <- 506
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")] <- 507
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")] <- 508
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")] <- 509
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")] <- 510
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")] <- 511
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 10 and < 20%")] <- 512
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 40 and < 50%")] <- 513
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 90 and <= 100%")] <- 514
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 10 and < 20%")] <- 515
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 40 and < 50%")] <- 516
landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 80 and < 90%")] <- 517  
  
#landcover 2008

landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] <- 500 
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")] <- 501
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] <- 502 
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")] <- 503
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")] <- 504   
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")] <- 505
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")] <- 506
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")] <- 507
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")] <- 508
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")] <- 509
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")] <- 510
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")] <- 511
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 10 and < 20%")] <- 512
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 40 and < 50%")] <- 513
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 90 and <= 100%")] <- 514
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 10 and < 20%")] <- 515
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 40 and < 50%")] <- 516
landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 80 and < 90%")] <- 517

#landcover 2010

landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] <- 500
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")] <- 501
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] <- 502
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")] <- 503
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")] <- 504
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")] <- 505
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")] <- 506
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")] <- 507
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")] <- 508
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")] <- 509
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")] <- 510
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")] <- 511
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 10%")] <- 512
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 50%")] <- 513
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 93%")] <- 514
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 10%")] <- 515
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 50%")] <- 516
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 57%")] <- 517
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 10%")] <- 518
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 50%")] <- 519
landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 91%")] <- 520


#landcover 2012

landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] <- 500
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")] <- 501
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] <- 502
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")] <- 503
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")] <- 504
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")] <- 505
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")] <- 506
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")] <- 507
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")] <- 508
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")] <- 509
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")] <- 510
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")] <- 511
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 10%")] <- 512
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 50%")] <- 513
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 93%")] <- 514
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 10%")] <- 515
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 50%")] <- 516
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 57%")] <- 517
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 10%")] <- 518
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 50%")] <- 519
landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 91%")] <- 520


#landcover 2014

landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] <- 500
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")] <- 501
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] <- 502
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")] <- 503
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")] <- 504
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")] <- 505
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")] <- 506
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")] <- 507
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")] <- 508
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")] <- 509
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")] <- 510
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")] <- 511
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 10%")] <- 512
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 50%")] <- 513
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 93%")] <- 514
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 10%")] <- 515
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 50%")] <- 516
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 57%")] <- 517
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 10%")] <- 518
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 50%")] <- 519
landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 91%")] <- 520


#landcover 2016

landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] <- 500
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")] <- 501
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] <- 502
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")] <- 503
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")] <- 504
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")] <- 505
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")] <- 506
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")] <- 507
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")] <- 508
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")] <- 509
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")] <- 510
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")] <- 511
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 10%")] <- 512
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 50%")] <- 513
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 93%")] <- 514
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 10%")] <- 515
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 50%")] <- 516
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 57%")] <- 517
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 10%")] <- 518
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 50%")] <- 519
landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 91%")] <- 520


```


Filter/Mask for non-desired categories

```{r}
#

leaflet() %>%
   addRasterImage(rc, opacity = 1, project = FALSE, group = "Land Cover 2016")


# all values > 0 and <= 0.25 become 1, etc.
m <- c(11, 498, NA, 516, 518, 1)
m
rclmat <- matrix(m, ncol=2, byrow=TRUE)
rclmat
rc <- reclassify(landcover2016, rclmat)
plot(rc)
```


```{r}
labels2<- c("Developed - Forested", "Developed - herbaceous or shrubland", "Developed - Medium Intensity", "Developed - High Intensity", "Cropland","Tree Cover 0-50%", "Tree Cover 50-100%", "Shrub Cover", "Herb Cover 0-50%", "Herb Cover 50-100%")

at = c(500,502,504,506,508,511,513,514,516,517,518)

#overlay census tracts and neighborhoods

pal2 <- leaflet::colorBin(palette = "Spectral",
                          bins = length(at),
                          domain = values(landcover2016), pretty = FALSE,
                          na.color = "white")

leaflet() %>%
  # addRasterImage(landcover2001, colors = pal2, opacity = 1, project = FALSE, group = "Land Cover 2001") %>%
  # addRasterImage(landcover2008, colors = pal2, opacity = 1, project = FALSE, group = "Land Cover 2008") %>%
  # addRasterImage(landcover2010, colors = pal2, opacity = 1, project = FALSE, group = "Land Cover 2010") %>%
  # addRasterImage(landcover2012, colors = pal2, opacity = 1, project = FALSE, group = "Land Cover 2012") %>%
  # addRasterImage(landcover2014, colors = pal2, opacity = 1, project = FALSE, group = "Land Cover 2014") %>%
   addRasterImage(landcover2016, colors = pal2, opacity = 1, project = FALSE, group = "Land Cover 2016") %>%
  # addRasterImage(landcoverchange10, opacity = 1, project = FALSE, group = "Land Cover Change 2010") %>%
  # addRasterImage(landcoverchange14, opacity = 1, project = FALSE, group = "Land Cover Change 2014") %>%
  # addRasterImage(bps2016, opacity = 1, project = FALSE, group = "Biophysical Settings 2016") %>%
  addLegend(pal = pal2, opacity = 1, values = at, labFormat = function(type, cuts, p) {paste0(labels2)}, group = "Land Cover Legend", title = "Land Cover Legend") %>%
  addLayersControl(
     overlayGroups = c("Wetlands", "Sandusky Bay Pathway", "Parks", "Land Cover Legend", "Sandusky Downtown Neighborhood Lines", "Land Cover 2001", "Land Cover 2008", "Land Cover 2010", "Land Cover 2012", "Land Cover 2014", "Land Cover 2016", "Land Cover Change 2010", "Land Cover Change 2014", "Biophysical Settings 2016"),
     options = layersControlOptions(collapsed = FALSE)
   ) 

```





