---
title: "Mapping-Rmd"
author: "Bouzaher, Julia"
date: "September 22, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's test the shapefile.


```{r}
library(rgeos)
library(sp)
library(sf)
library(rgeos)
library(magrittr)
library(dplyr)
library(readr)
library(gridExtra)
library(ggplot2)
library(data.table)
library(rgdal)
library(lubridate)
library(stringr)
library(rgdal)
library(sf) 
library(sp)
library(rgeos)
library(leaflet)
library(raster)
library(dplyr)
library(lwgeom)
library(spatialEco)
library(stats)

```

```{r}
shape <- read_sf("data/source/external/tract shapefiles [tract]/tl_2019_39_tract.shp") %>%
  filter(COUNTYFP =="043")

factpal <- colorFactor(palette = magma(19), domain = shape$TRACTCE)
 
# leaflet(shape) %>%
#   addProviderTiles(providers$OpenStreetMap) %>%
#   addPolygons(weight=1.4, fillColor = ~factpal(shape$TRACTCE), fillOpacity = 1

final <- full_join(final,shape, by="NAMELSAD") %>%
  mutate(tract = NAMELSAD) %>%
  dplyr::select(-(c(STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,INTPTLON,INTPTLAT))) %>%
  mutate(medianincome = as.numeric(final$`Median household income`))


final <- st_sf(final)
final <- st_transform(final, 4326)
```

Map 1: Distribution of Black/African American Population

```{r}

factpal <- viridis(length(final$Black))
factpal <- colorNumeric(palette = viridis(997), c(0,997))

#final <- final %>% filter(year == "2016")

leaflet(final) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(weight=1.4, fillColor = ~factpal(as.numeric(final$Black) ), fillOpacity=1) %>%
  addLegend(position ="bottomleft", pal = factpal, values = as.numeric(final$Black), title = "Number of Black Individuals",labFormat = labelFormat(suffix = " individuals"), opacity=1)


```

Map 2: Distribution of Median Rents

```{r}

range(final$MedianRent)
factpal <- colorNumeric(palette = viridis(500), c(500,1000))

map <- leaflet(final %>% filter(year == "2018")) %>%
  addTiles() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(label = ~paste ("Tract:",tract, "\nMedian Rent:",MedianRent),
              fillColor = ~factpal(as.numeric(MedianRent)),
              weight = 1,
              smoothFactor = 0.5,
              opacity = 1.0,
              fillOpacity = .88,
              highlightOptions = highlightOptions(color = "white",
                                                  weight = 2,
                                                  bringToFront = TRUE)) %>%
  addLegend(position ="bottomleft", pal = factpal, values = as.numeric(final$MedianRent), title = "Median Rents 2018",labFormat = labelFormat(prefix = "$"), opacity=1)

```

Let's take a look at our other files.

```{r}
real_estate_db <- read_csv("data/source/external/mortgage [county]/real_estate_db.csv") %>%
  filter(state=="Ohio") %>%
  filter(city=="Sandusky")
``` 

```{r}
GLRI <- read_sf("data/source/city/GLRI Pathway/Polygon_layer.shp")
GLRI <- st_transform(GLRI, 4326)

leaflet(GLRI) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons()

```

```{r}
Landmarks <- read_sf("data/source/city/Landmarks/Landmarks_ft.shp")
Landmarks <- st_transform(Landmarks, 4326)

leaflet(Landmarks) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addCircleMarkers(radius=.2)

```


```{r}
# Model_Blocks <- read_sf("data/source/city/Model_Blocks/Model_Blocks.shp")
# Model_Blocks <- st_transform(Model_Blocks, 4326)
# 
# leaflet(Model_Blocks) %>%
#   addProviderTiles(providers$OpenStreetMap) %>%
#   addPolygons()

```

```{r}
Neighborhoods <- read_sf("data/source/city/Neighborhoods/City_of_Sandusky_Neighborhoods.shp")
Neighborhoods <- st_transform(Neighborhoods, 4326)

leaflet(Neighborhoods) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons()

```

```{r}
Erie_County_Plan <- read_sf("data/source/city/Sandusky Bay Pathway/2014_Erie_County_Plan.shp")
Erie_County_Plan <- st_transform(Erie_County_Plan, 4326)

leaflet(Erie_County_Plan) %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons()

```





```{r}

#wetlands data

library(raster)
Wetlands <- read_sf("data/source/external/wetlands data/HU8_04100011_Watershed/HU8_04100011_Wetlands.shp")
Wetlands2 <- read_sf("data/source/external/wetlands data/HU8_04100012_Watershed/HU8_04100012_Wetlands.shp")

Wetlands <- st_transform(Wetlands, CRS("+init=epsg:4326"))
Wetlands2 <- st_transform(Wetlands2, CRS("+init=epsg:4326"))

Wetlands3 <- rbind(Wetlands, Wetlands2)

Wetlands3 <- st_crop(Wetlands3, xmin = -82.918968, xmax = -82.314877,  ymin = 41.277963, ymax = 41.483993)


#parks names data
parks <- fread("data/source/external/Parks/OH_Features_20200901.txt") %>%
  filter(COUNTY_NAME == "Erie") %>%
  filter(FEATURE_CLASS == "Park") %>%
  rename(lat = PRIM_LAT_DEC, long = PRIM_LONG_DEC)

#land cover data



leafIcons <- icons(
  iconUrl = 
    "http://leafletjs.com/examples/custom-icons/leaf-green.png",
  iconWidth = 15, iconHeight = 40,
  iconAnchorX = 14, iconAnchorY = 40
)


```




```{r}
library(rgeos)
library(sp)
library(sf)
library(rgeos)
library(magrittr)
library(dplyr)
library(readr)
library(gridExtra)
library(ggplot2)
library(data.table)
library(rgdal)
library(lubridate) 
library(stringr)
library(rgdal)
library(sf) 
library(sp)
library(rgeos)
library(leaflet)
library(raster)
library(dplyr)
library(maptools)
library(lwgeom)
library(spatialEco)
library(stats)

```


```{r}

landcover2016 <- raster::raster("data/source/external/landcover data/US_200EVC/us_200evc/w001001.adf")

landcover2014 <- raster::raster("data/source/external/landcover data/US_140EVC/us_140evc/w001001.adf")

landcover2012 <- raster::raster("data/source/external/landcover data/US_130EVC/us_130evc/w001001.adf")

landcover2010 <- raster::raster("data/source/external/landcover data/US_120EVC/us_120evc/w001001.adf")

landcover2008<- raster::raster("data/source/external/landcover data/US_110EVC/us_110evc/w001001.adf")

landcover2001 <- raster::raster("data/source/external/landcover data/US_105EVC/us_105evc/w001001.adf") 

```


Filter/Mask for non-desired categories

```{r}
# labels22001<- c("Developed - Forested", "Developed - herbaceous or shrubland", "Developed - Low Intensity", "Developed - Medium Intensity", "Developed - High Intensity", "Herbaceous Wetlands", "Tree Cover 0-50%", "Tree Cover 50-100%", "Herb Cover 0-50%", "Herb Cover 50-100%", "Shrub Cover", "Cropland", "Barren or Quarry Land")

#landcover 2001
landcover2001@data@attributes[[1]]$ID
landcover2001@data@attributes[[1]]$CLASSNAMES
length(landcover2001@data@attributes[[1]]$ID)

a <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")]
b <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")]
c <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] 
d <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")]
e <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")]   
f <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")]
g <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")]
h <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Orchard")]
i <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")]
j <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")]
k <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")]
l <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Fallow/Idle Cropland")]
m <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "NASS-Pasture and Hayland")]
n <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Pasture/Hay")]
o <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Cultivated Crops")]
p <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 10 and < 20%")]
q <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 40 and < 50%")]
r <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 90 and <= 100%")]
s <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 10 and < 20%")]
t <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 40 and < 50%")]
u <- landcover2001@data@attributes[[1]]$ID[which(landcover2001@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 80 and < 90%")]

rangemin <- c(g,f,a,d,h,p,q,s,t)
rangemax <- c(g,f,c,e,o,q,r,t,u)

c(h,o)
labels2<- c("Developed - Medium/High Intensity","Developed - Low/Medium Intensity","Developed - Forested", "Developed - herbaceous or shrubland", "Cropland","Tree Cover 0-50%", "Tree Cover 50-100%","Herb Cover 0-50%", "Herb Cover 50-100%", "NA")

rc <- data.frame(cbind(rangemin, rangemax,1:9))
rc <- rbind(rc,c(0, 11, NA), c(18, 22, NA),c(25, 59, NA), c(83,100,NA), c(110,120,NA), c(18, 21, NA), c(129,450,NA))
rcmat <- as.matrix(rc)
rcmat

xxxxxx <- reclassify(landcover2001, rcmat, right=NA)

```

```{r}
#landcover 2008
landcover2008@data@attributes[[1]]$ID
landcover2008@data@attributes[[1]]$CLASSNAMES
length(landcover2008@data@attributes[[1]]$ID)

a <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] 
b <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")]
c <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] 
d <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")]
e <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")]   
f <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")]
g <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")]
h <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Orchard")]
i <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")]
j <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")]
k <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")]
l <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Fallow/Idle Cropland")]
m <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "NASS-Pasture and Hayland")]
n <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Pasture/Hay")]
o <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Cultivated Crops")]
p <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 10 and < 20%")]
q <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 40 and < 50%")]
r <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 90 and <= 100%")]
s <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 10 and < 20%")]
t <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 40 and < 50%")]
u <- landcover2008@data@attributes[[1]]$ID[which(landcover2008@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 80 and < 90%")]

rangemin <- c(g,f,a,d,h,p,q,s,t)
rangemax <- c(g,f,c,e,o,q,r,t,u)


labels2<- c("Developed - Medium/High Intensity","Developed - Low/Medium Intensity","Developed - Forested", "Developed - herbaceous or shrubland", "Cropland","Tree Cover 0-50%", "Tree Cover 50-100%","Herb Cover 0-50%", "Herb Cover 50-100%", "NA")

rc <- data.frame(cbind(rangemin, rangemax,1:9))
rc <- rbind(rc,c(0, 11, NA), c(18, 22, NA),c(25, 59, NA), c(83,100,NA), c(110,120,NA), c(18, 21, NA), c(129,450,NA))
rcmat <- as.matrix(rc)
rcmat


xxxxx <- reclassify(landcover2008, rcmat,right=NA)

```

```{r}
#landcover 2010
landcover2010@data@attributes[[1]]$ID
landcover2010@data@attributes[[1]]$CLASSNAMES
length(landcover2010@data@attributes[[1]]$ID)

a <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] 
b <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")]
c <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] 
d <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")]
e <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")]   
f <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")]
g <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")]
h <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")]
i <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")]
j <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 10 and < 20%")]
k <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 40 and < 50%")]
l <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 90 and <= 100%")]
m <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 10 and < 20%")]
n <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 40 and < 50%")]
o <- landcover2010@data@attributes[[1]]$ID[which(landcover2010@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 80 and < 90%")] 

rangemin <- c(g,f,a,d,i,j,k,m,n)
rangemax <- c(h,g,c,e,i,k,l,n,o)

labels2<- c("Developed - Medium/High Intensity","Developed - Low/Medium Intensity","Developed - Forested", "Developed - herbaceous or shrubland", "Cropland","Tree Cover 0-50%", "Tree Cover 50-100%","Herb Cover 0-50%", "Herb Cover 50-100%", "NA")

rc <- data.frame(cbind(rangemin, rangemax,1:9))
rc <- rbind(rc,c(0, 11, NA), c(18, 21, NA), c(25, 63, NA), c(65, 100, NA),c(110, 120, NA),c(129,450,NA),c(31,31,NA))
rcmat <- as.matrix(rc)
rcmat

xxxx <- reclassify(landcover2010, rcmat,right=NA)


```


```{r}
#landcover 2012
landcover2012@data@attributes[[1]]$ID
landcover2012@data@attributes[[1]]$CLASSNAMES
length(landcover2012@data@attributes[[1]]$ID)

a <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] 
b <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")]
c <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] 
d <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")]
e <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")]   
f <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")]
g <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")]
h <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")]
i <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")]
j <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")]
k <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")]
l <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 10 and < 20%")]
m <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 40 and < 50%")]
n <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 90 and <= 100%")]
o <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 10 and < 20%")]
p <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 40 and < 50%")]
q <- landcover2012@data@attributes[[1]]$ID[which(landcover2012@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 80 and < 90%")]  

rangemin <- c(g,f,a,d,i,l,m,o,p)
rangemax <- c(h,g,c,e,k,m,n,p,q)

labels2<- c("Developed - Medium/High Intensity","Developed - Low/Medium Intensity","Developed - Forested", "Developed - herbaceous or shrubland", "Cropland","Tree Cover 0-50%", "Tree Cover 50-100%","Herb Cover 0-50%", "Herb Cover 50-100%", "NA")

rc <- data.frame(cbind(rangemin, rangemax,1:9))
rc <- rbind(rc,c(0, 11, NA),c(25, 63, NA), c(18, 21, NA), c(69,100,NA), c(110,120,NA), c(129,450,NA))
rcmat <- as.matrix(rc)
rcmat

xxx <- reclassify(landcover2012, rcmat,right=NA)

```


```{r}
#landcover 2014
landcover2014@data@attributes[[1]]$ID
landcover2014@data@attributes[[1]]$CLASSNAMES
length(landcover2014@data@attributes[[1]]$ID)

a <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")] 
b <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")]
c <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")] 
d <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")]
e <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")]   
f <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")]
g <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")]
h <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")]
i <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")]
j <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")]
k <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")]
l <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")]
m <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 10 and < 20%")]
n <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 40 and < 50%")]
o <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Tree Cover >= 90 and <= 100%")]
p <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 10 and < 20%")]
q <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 40 and < 50%")]
r <- landcover2014@data@attributes[[1]]$ID[which(landcover2014@data@attributes[[1]]$CLASSNAMES == "Herb Cover >= 80 and < 90%")]  

rangemin <- c(g,f,a,d,i,m,n,p,q)
rangemax <- c(h,g,c,e,l,n,o,q,r)

labels2<- c("Developed - Medium/High Intensity","Developed - Low/Medium Intensity","Developed - Forested", "Developed - herbaceous or shrubland", "Cropland","Tree Cover 0-50%", "Tree Cover 50-100%","Herb Cover 0-50%", "Herb Cover 50-100%", "NA")

rc <- data.frame(cbind(rangemin, rangemax,1:9))
rc <- rbind(rc,c(0, 11, NA), c(18,21,NA), c(25,62,NA), c(69,100,NA), c(109,120,NA),c(129,450,NA))
rcmat <- as.matrix(rc)
rcmat

xx <- reclassify(landcover2014, rcmat, right=NA)

```

```{r}
#landcover 2016
landcover2016@data@attributes[[1]]$ID
landcover2016@data@attributes[[1]]$CLASSNAMES
length(landcover2016@data@attributes[[1]]$ID)

a <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Deciduous Forest")]
b <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Evergreen Forest")]
c <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Mixed Forest")]
d <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Herbaceous")]
e <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed-Upland Shrubland")]
f <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed - Low Intensity")]
g <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed - Medium Intensity")]
h <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Developed - High Intensity")]
i <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop-Close Grown Crop")]
j <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Row Crop")]
k <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Close Grown Crop")]
l <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "NASS-Wheat")]
m <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 10%")]
n <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 50%")]
o <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Tree Cover = 93%")]
# p <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 10%")]
# q <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 50%")]
# r <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Shrub Cover = 57%")]
s <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 10%")]
t <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 50%")]
u <- landcover2016@data@attributes[[1]]$ID[which(landcover2016@data@attributes[[1]]$CLASSNAMES == "Herb Cover = 91%")]

rangemin <- c(g,f,a,d,i,m,n,s,t)
rangemax <- c(h,g,d,e,l,n,o,t,u)

labels2<- c("Developed - Medium/High Intensity","Developed - Low/Medium Intensity","Developed - Forested", "Developed - herbaceous or shrubland", "Cropland","Tree Cover 0-50%", "Tree Cover 50-100%","Herb Cover 0-50%", "Herb Cover 50-100%", "NA")

rc <- data.frame(cbind(rangemin, rangemax,1:9))
rc <- rbind(rc,c(0, 13, NA), c(18,21,NA), c(25,62,NA),c(69,109,NA), c(193,309,NA), c(392,450,NA))
rcmat <- as.matrix(rc)
rcmat

x <- reclassify(landcover2016, rcmat,right=NA)

```


Visualizing the Rasters

```{r}
pal1<- leaflet::colorFactor(palette = "Spectral", domain = values(x), na.color = "transparent")
pal2 <- leaflet::colorFactor(palette = "Spectral", domain = values(xx), na.color = "transparent")
pal3 <- leaflet::colorFactor(palette = "Spectral", domain = values(xxx), na.color = "transparent")
pal4 <- leaflet::colorFactor(palette = "Spectral", domain = values(xxxx), na.color = "transparent")
pal5 <- leaflet::colorFactor(palette = "Spectral", domain = values(xxxxx), na.color = "transparent")
pal6 <- leaflet::colorFactor(palette = "Spectral", domain = values(xxxxxx), na.color = "transparent")


leaflet() %>%
  addRasterImage(x, pal1, opacity = 1, project = FALSE, group = "Land Cover 2016") %>%
  addRasterImage(xx, pal2, opacity = 1, project = FALSE, group = "Land Cover 2014") %>%
  addRasterImage(xxx, pal3, opacity = 1, project = FALSE, group = "Land Cover 2012") %>%
  addRasterImage(xxxx, pal4, opacity = 1, project = FALSE, group = "Land Cover 2010") %>%
  addRasterImage(xxxxx, pal5, opacity = 1, project = FALSE, group = "Land Cover 2008") %>%
  addRasterImage(xxxxxx, pal6, opacity = 1, project = FALSE, group = "Land Cover 2001") %>%
  addLegend(pal = pal4, opacity = 1, values = values(xxxx), labFormat = function(type, cuts, p) {paste0(labels2)}, group = "Land Cover  Legend", title = "Land Cover Legend") %>%
  addLayersControl(
     overlayGroups = c("Land Cover 2001", "Land Cover 2008", "Land Cover 2010", "Land Cover 2012", "Land Cover 2014", "Land Cover 2016"),
     options = layersControlOptions(collapsed = TRUE))

```